## Reading

```{r}
# Load libraries
library(ggplot2)
library(gridExtra)
```

```{r}
# getwd()
# list.files()
pf <- read.csv("./datasets/pseudo_facebook.tsv", sep="\t")
names(pf)


qplot(x = dob_day, data=pf) +
  scale_x_continuous(breaks=1:31) +
  facet_wrap(~dob_month, ncol = 3)
```

# friend count
```{r}
qplot(x = friend_count, data=pf, xlim=c(0,1000))

# yet another way to limit data
qplot(x = friend_count, data=pf) +
  scale_x_continuous(limits=c(0,1000))
```
# Adjusting the bin width
```{r}
qplot(x = friend_count, data=pf, binwidth=25) +
  scale_x_continuous(limits=c(0,1000), breaks=seq(0,1000,50)) +
  facet_wrap(~gender)
```

# Omitting NA observations by applying subset
```{r}
qplot(x = friend_count, data=subset(pf,!is.na(gender)), binwidth=25) +
  scale_x_continuous(limits=c(0,1000), breaks=seq(0,1000,50)) +
  facet_wrap(~gender)
```

# Stats of friends count
```{r}
table(pf$gender)
by(pf$friend_count,pf$gender, summary)
````

# Tenure
```{r}
qplot(x=tenure, data=pf, binwidth=30,
  color = I('black'), fill =I('#099DD9'))
```

# Tenure by year
```{r}
qplot(x=tenure/365, data=pf, binwidth=.25,
      color = I('black'), fill =I('#F79420')) +
      scale_x_continuous(breaks = seq(1,7,1), limits=c(0,7))
```

# Labeling plots
```{r}
qplot(x=tenure/365, data=pf, binwidth=.25,
      xlab = "Numbers of years using fb",
      ylab = "Numbers of users in Sample",
      color = I('black'), fill =I('#F79420')) +
  scale_x_continuous(breaks = seq(1,7,1), limits=c(0,7))
```

# User Ages
```{r}
qplot(x=age, data=pf, binwidth=1,
      xlab = "Age",
      ylab = "Users in Sample",
      color = I('#5600b3'),fill =I('#e5ccff')) +
  scale_x_continuous(breaks = seq(12,113,5), limits=c(0,113))
```

# Transforming Data
```{r}

qplot(x=friend_count, data=pf)
summary(pf$friend_count)

summary(log10(pf$friend_count + 1))

summary(sqrt(pf$friend_count))
```

# Transforming Data Quiz
```{r}
p1 = ggplot(aes(x=friend_count), data=pf) + geom_histogram()
p2 = p1 + scale_x_log10()
p3 = p1 + scale_x_sqrt()

grid.arrange(p1, p2, p3, ncol=1)
```

# Frequency Polygons 
```{r}
qplot(x=friend_count, data =subset(pf, !is.na(gender)), 
      bindwidth=10, geom='freqpoly', color =gender) + 
  scale_x_continuous(limits=c(0,1000), breaks=seq(0,1000,50))
```

# Who was more friends on Average? 
```{r}
qplot(x=friend_count,y = ..count../sum(..count..), 
      data =subset(pf, !is.na(gender)), 
      xlab = ('friend_count'),
      ylab = ('Proportion of users w/ friend count'),
      bindwidth=10, geom='freqpoly', color =gender) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))
```

# Which gender make more likes in the www? 
```{r}
summary(pf$www_likes)
qplot(x=www_likes,
      data =subset(pf, !is.na(gender)), 
      xlab = ('friend_count'),
      ylab = ('Proportion of users w/ www_likes count'),
      bindwidth=10, geom='freqpoly', color =gender) + 
  scale_x_continuous() + scale_x_log10()
```

```{r}
by(pf$www_likes, pf$gender, sum)
```
# Box Plots 
```{r}
qplot(x=gender, y=friend_count,
        data =subset(pf, !is.na(gender)), 
        geom='boxplot',
        ylim = c(0, 1000))

qplot(x=gender, y=friend_count,
      data =subset(pf, !is.na(gender)), 
      geom='boxplot') + 
      scale_y_continuous(limits=c(0,1000))

qplot(x=gender, y=friend_count,
      data =subset(pf, !is.na(gender)), 
      geom='boxplot') + 
  coord_cartesian(ylim =c(0,1000))
```

```{r}
qplot(x=gender, y=friend_count,
      data =subset(pf, !is.na(gender)), 
      geom='boxplot') + 
  coord_cartesian(ylim =c(0,250))
```

```{r}
by(pf$friend_count, pf$gender, summary)
```


# Who initiated friendship? 
```{r}
by(pf$friendships_initiated, pf$gender, summary)
qplot(x=gender, y=friendships_initiated,
      data =subset(pf, !is.na(gender)), 
      geom='boxplot') + 
  coord_cartesian(ylim =c(0,150))
```

# Getting logical
```{r}
summary(pf$mobile_likes)

mobile_checkins <- NA
pf$mobile_checkin <- ifelse(pf$mobile_likes > 0, 1, 0)
pf$mobile_checkin <- factor(pf$mobile_checkin)
sum(pf$mobile_checkin == 1)/length(pf$mobile_checkin)*100
```