```{r}
# Load libraries
library(ggplot2)
library(dplyr)
```

```{r}
pf <- read.csv("../datasets/pseudo_facebook.tsv", sep="\t")
```

# Scatter Plots
```{r}
qplot(x = age, y = friend_count, data= pf)

# another way
qplot(age, friend_count, data=pf)
```

# ggplot syntax
```{r}
ggplot(aes(x=age, y=friend_count), data = pf) + geom_point() +
 xlim(13,90)
summary(pf$age)
```

# Overplotting
# Whenever there is toomany points over a region
```{r}
ggplot(aes(x=age, y=friend_count), data = pf) +
  geom_jitter(alpha=1/20) +
  xlim(13,90) 

```
# Let's transform the Y axis by using coord_trans
```{r}
ggplot(aes(x=age, y=friend_count), data=pf) +
  geom_point(alpha=1/20, position=position_jitter(h=0)) +
  xlim(13,90) + 
  coord_trans(y = "sqrt")
```
# Alpha and  Jitter
Explore the relationship between friends initiated vs age 
```{r}
ggplot(aes(x=age, y=friendships_initiated), data=pf) +
  geom_jitter(alpha=1/10, position = position_jitter(h=0)) + 
  coord_trans(y="sqrt")
```

# Conditional Means
```{r}
age_groups <- group_by(pf, age)
pf.fc_by_age <- summarise(age_groups, 
          friend_count_mean=mean(friend_count),
          friend_count_median=median(friend_count),
          n=n())

pf.fc_by_age <- arrange(pf.fc_by_age, age)
head(pf.fc_by_age)
```

# Another way to do it :) 
```{r}
pf.fc_by_age <- pf %>% 
  group_by(age) %>% 
  summarise(friend_count_mean=mean(friend_count),
          friend_count_median=median(friend_count),
          n=n()) %>% 
  arrange(age)

head(pf.fc_by_age, 20)
```

```{r}
ggplot(aes(x=age, y=friend_count_mean), data=pf.fc_by_age) +
  geom_line(position=position_jitter(h=0))
```

#OVerlay summaries with Raw Data
```{r}
ggplot(aes(x=age, y=friend_count), data=pf) + 
  coord_cartesian(xlim=c(13,90), ylim=c(0,1000)) + 
  geom_point(alpha=0.05, 
             position=position_jitter(h=0),
             color='orange') + 
  geom_line(stat="summary", fun.y=mean, color="red") + 
  geom_line(stat="summary", fun.y=quantile, fun.args=list(probs=0.1), linetype=2,color="blue") +
  geom_line(stat="summary", fun.y=quantile, fun.args=list(probs=0.5), color="blue") + 
  geom_line(stat="summary", fun.y=quantile, fun.args=list(probs=0.9), linetype=2,color="blue")
```

```{r}
cov_pf = cov(x=pf$age,y=pf$friend_count, method="pearson")
std_x = sd(pf$age)
std_y = sd(pf$friend_count)

r = cov_pf / (std_x * std_y)
r

# using cor.test
cor.test(x = pf$age,y = pf$friend_count, method="pearson")

# using with 
with(pf, cor.test(x = age,y = friend_count, method="pearson"))
```
# Using monotonic functions
```{r}
# using with 
with(data = subset(pf, age<=70), cor.test(x = age,y = friend_count, method="pearson"))
```
